data:
  name: "celeba64"
  img_ch: 3
  img_size: 64
  path: _data/CelebA/processed64
  num_classes: 10
  class_condition: true
  num_workers: 2
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
train:
  lr1: 3e-4
  lr2: 3e-4
  batch_size1: 16
  batch_size2: 4096
  epochs1: 1
  epochs2: 15
  max_physical_batch_size: 10
  num_noise_sample: 4
  ema_rate: 0.9999
  ckpt_path: _pretrained_models/imagenet64.ckpt
  seed: 42
sample:
  type: ddim
  samplesteps: 200
  rho: 1.
  batch_size: 256
  guide_scale: 0.
  seed: 42
model:
  ch: 128
  ch_mult: [1, 2, 2, 2, ]
  num_res_blocks: 2
  dropout: 0.
  attn: [2, ]
dp:
  max_grad_norm: 0.01
  delta: 1e-6
  epsilon: 1.0
  S: 950
  sigma: 2.83
